{
 "title": "Nginx",
 "description": "Shows stats built from the Prometheus Nginx plugin.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Connections handled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_handled{instance=~\"$instance.*\"}",
     "legendFormat": "{{ stage }}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Reading connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Writing connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance.*\"}"
    }
   ]
  }
 ]
}