{
 "title": "Server Health Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Welcome to the Server Health Status Dashboard\n\nThis view shows the operational systems health across the production environment. (*need to add further instructions* and elaboration around each panel below)"
  },
  {
   "title": "Health of Nodes",
   "type": "graph",
   "description": "Shows the number of nodes receiving data at any given time.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Receiving data" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "CPU Utilization (5 Minute Average)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[5m])))"
    }
   ]
  },
  {
   "title": "Server Load",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Server Load( 5 minutes Average)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization in  Detail ( 5 minutes Average)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])"
    }
   ]
  },
  {
   "title": "Cached RAM Utilization",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "((node_memory_Cached_bytes + node_memory_Slab_bytes) / (node_memory_MemTotal_bytes )) * 100"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=~\"/dev/.*\"}"
    }
   ]
  },
  {
   "title": "RAM Utilization (not counting cached)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - (node_memory_Cached_bytes + node_memory_Slab_bytes) - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes )) * 100"
    }
   ]
  }
 ]
}